export enum Type {
    SALAIRE = "SALAIRE",
    REVENU_LOCATIF = "REVENU_LOCATIF",
    DIVIDENDES = "DIVIDENDES",
    INTERETS = "INTERETS",
    REVENU_VENTES = "REVENU_VENTES",
    ALLOCATION_FAMILIALE = "ALLOCATION_FAMILIALE",
    PRIME = "PRIME",
    DROITS_AUTEUR = "DROITS_AUTEUR",
    AFFILIATIONS = "AFFILIATIONS",
    INVESTISSEMENTS_IMMOBILIERS = "INVESTISSEMENTS_IMMOBILIERS",
    AUTRES = "AUTRES"
}